---
upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: supermarket_sales

cleaned-upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: table1
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: table2
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: table3

sqljoin:
  export:
    - export:
        host: s3
        bucket: end2enddsproject
        filename: cleaned_supermarket

model:
  export:
    - export:
        host: gsheet
        spread_sheet_id: 1mHw-uzkqThGeNJvnJt6L1fcwTddBc5cJ5Xo0ib5gdHk
        worksheet_name: Sheet1